In [2]:
import numpy as np
from math import sin, cos, pi

O = np.array([[0, 0]])
O_ = np.array([[0,100]])

theta = 5*pi/4
B = np.array([[cos(theta), -sin(theta)], [sin(theta), cos(theta)]]) # right
B_ = np.array([[cos(-theta), -sin(-theta)], [sin(-theta), cos(-theta)]]) # left

[[-1.42108547e-14  6.66665930e+01]]


In [3]:
newO = O_ - O

In [46]:
lev0 = newO@B_
lev0

array([[ 70.71067812, -70.71067812]])

In [54]:
lev0_ = newO@B
lev0_

array([[-70.71067812, -70.71067812]])

In [47]:
# first level of branches
b0 = (lev0*2/3) 
b0

array([[ 47.14045208, -47.14045208]])

In [55]:
# first level of branches
b0_ = (lev0_*2/3) 
b0_

array([[-47.14045208, -47.14045208]])

In [49]:
# second level of branches
b1 = (b0*2/3)@B_
b1

array([[-4.44444444e+01,  1.42108547e-14]])

In [56]:
# second level of branches
b1_ = (b0_*2/3)@B
b1_

array([[4.44444444e+01, 1.42108547e-14]])

In [52]:
# third leve of branches
b2 = (b1*2/3)@B_
b2

array([[20.95131204, 20.95131204]])

In [57]:
# third leve of branches
b2_ = (b1_*2/3)@B
b2_

array([[-20.95131204,  20.95131204]])

In [50]:
B_

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [51]:
B

array([[-0.70710678,  0.70710678],
       [-0.70710678, -0.70710678]])